<?php

declare(strict_types=1);

return [
    'hero_title' => 'Lufly Platform',
    'hero_subtitle' => 'An enterprise multilingual foundation built with native PHP — modular, secure and ready to scale.',
    'cta_products' => 'Browse products',
    'cta_admin' => 'Open admin panel',
    'features_title' => 'What is included',
    'feature_modules' => 'Modular architecture',
    'feature_modules_desc' => 'Products, users, media, settings and more — each module ships controllers, services, repositories and views.',
    'feature_localization' => 'Unlimited localization',
    'feature_localization_desc' => 'Static translations, dynamic entity translations and fully translated URLs.',
    'feature_api' => 'Standards-based API',
    'feature_api_desc' => 'Consistent success/error envelopes, pagination metadata and auto-generated documentation.',
    'hero1_eyebrow' => 'LUFLY · TIDAL MONOLITH SYSTEM', 'hero1_primary' => 'See Smart Toilets', 'whatsapp_specifier' => 'WhatsApp Specifier',
    'hero2_eyebrow' => 'LUFLY · HYDRODYNAMIC FLOW', 'hero2_primary' => 'View All Mixers', 'hero2_secondary' => 'Explore 6 PVD Finishes',
    'hero3_eyebrow' => 'LUFLY · SPATIAL ARCHITECTURE', 'hero3_primary' => 'Explore Sanctuaries', 'hero3_secondary' => 'Request BIM Models',
    'hero4_eyebrow' => 'LUFLY · HYDROTHERAPY WELLNESS', 'hero4_primary' => 'Discover Showers', 'hero4_secondary' => 'Hydrodynamic Rituals',
    'trust_kicker' => 'Our advantage', 'trust_title_before' => 'Built for a', 'trust_title_emphasis' => 'Better', 'trust_title_after' => 'Tomorrow', 'trust_subtitle' => 'European quality. Sustainable innovation. Global reach.', 'year' => 'YEAR',
    'trust_guarantee_title' => 'Factory Guarantee', 'trust_guarantee_desc' => 'Rigorous European EN 997 & EN 817 quality certification with 400 kg load tolerance.', 'trust_water_title' => 'PRO-ECO Hydrodynamics', 'trust_water_desc' => 'Swiss Neoperl® precision aerators saving up to 45% water without compromising volume.', 'trust_ceramic_title' => 'Vitreous Ceramic', 'trust_ceramic_desc' => 'Sub-0.35% water absorption rate with poreless nano-antibacterial hygienic glazing.', 'trust_global_title' => 'Global Markets', 'trust_global_desc' => 'Strategic export dispatch from Gaziantep manufacturing facilities to 34+ global markets.', 'trust_footer' => 'Quality today. A cleaner tomorrow.',
    'finishes_tag' => 'Surface Metallurgy & Finishes', 'finishes_title_before' => 'Choose the', 'finishes_title_emphasis' => 'Finish', 'finishes_title_after' => 'of Your Space', 'finishes_desc' => 'Six architectural finishes engineered with Physical Vapor Deposition (PVD) technology for exceptional durability, refined aesthetics, and long-lasting resistance to scratches, corrosion, and harsh environments.', 'finishes_note_1' => 'Finishes', 'finishes_note_2' => 'that endure', 'finishes_note_3' => 'beauty', 'finishes_note_4' => 'that lasts', 'finish_inquire' => 'Inquire This Finish via WhatsApp', 'view_mixers' => 'View All Mixers',
    'collections_tag' => 'Curated Collections', 'design_title' => 'Design Your Space', 'design_desc' => 'Engineered ceramic suites, tapware, and wellness fixtures designed for monolithic architectural harmony.', 'category_toilets' => 'Toilets & Bidets', 'category_toilets_desc' => 'Rimless EN 997 China · Soft-Close', 'category_basins' => 'Washbasins', 'category_basins_desc' => 'Countertop & Monolithic Sinks', 'category_mixers' => 'Faucets & Mixers', 'category_mixers_desc' => 'Solid Brass · PVD Finishes', 'category_showers' => 'Concealed Showers', 'category_showers_desc' => 'Thermostatic 38°C Safety Core', 'category_commercial' => 'Commercial Sanitary', 'category_commercial_desc' => 'Radar Sensor Urinals & Fittings',
    'inspiration_tag' => 'Spatial Showcase', 'inspiration_title' => 'Get Inspired', 'inspiration_desc' => 'Explore real architectural installations featuring LUFLY fixtures in luxury residential and hospitality environments.', 'inspiration_1_tag' => 'Spa & Wellness', 'inspiration_1_title' => 'The Calacatta Executive Suite', 'inspiration_1_desc' => 'Freestanding soaking tub paired with brushed gold floor-mounted mixer and monolithic vitreous sanitary ware.', 'inspiration_2_tag' => 'Minimalist Living', 'inspiration_2_title' => 'The Minimalist Oak En-Suite', 'inspiration_2_desc' => 'Matte black concealed tapware creating a tactile contrast against natural micro-cement and warm timber.', 'inspiration_3_tag' => 'Architectural Powder Room', 'inspiration_3_title' => 'The Serene Japandi Retreat', 'inspiration_3_desc' => 'Pristine white ceramic vessel basin with high-rise rose gold faucet and atmospheric indirect lighting.', 'inspiration_4_tag' => 'Gourmet Architecture', 'inspiration_4_title' => 'The Contemporary Culinary Suite', 'inspiration_4_desc' => 'Architectural pull-out dual-spray chef mixer in brushed steel over an undermount composite quartz sink.',
    'rituals_tag' => 'Hydrodynamic Engineering', 'rituals_title' => 'Water Rituals Shaped by Precision', 'rituals_desc' => 'Every drop is choreographed to deliver sensory comfort, silent operation, and responsible conservation.', 'ritual_1_label' => 'HYDRODYNAMIC FLOW', 'ritual_1_title' => 'Air-Infused Crystal Stream', 'ritual_1_desc' => 'Precision aeration enriches the water stream with micro-bubbles of air, creating a velvety, dense flow that eliminates splashing and cuts water consumption by up to 45%.', 'ritual_1_metric' => 'Pro-Eco 5.7 L/min Standard', 'ritual_2_label' => 'CERAMIC DISCS', 'ritual_2_title' => '500,000 Cycle Durability', 'ritual_2_desc' => 'Diamond-hard ceramic discs from Kerox® Hungary guarantee leak-free operation, buttery lever movement, and complete resistance to aggressive limescale and mineral deposits.', 'ritual_2_metric' => 'Zero Drift · Class 1 Acoustic', 'ritual_3_label' => 'THERMOSTAT SAFETY', 'ritual_3_title' => 'Instant 0.2s Temperature Balance', 'ritual_3_desc' => 'Concealed thermostatic cartridges respond to pressure shifts in 0.2 seconds, holding water precisely at 38°C to eliminate cold shocks and scalding risks for hotel guests and families.', 'ritual_3_metric' => '38°C Safety Lock Standard',
    'featured_tag' => 'Masterpiece Registry', 'featured_title' => 'Featured Architectural Fixtures', 'full_catalog' => 'View Full Catalog (280+ Fixtures)', 'inquire_b2b' => 'Inquire B2B', 'corporate_badge' => 'Official Manufacturer Entity', 'spec_desk_title' => 'Architectural Specification Desk', 'spec_desk_cta' => 'Request Architect Tender Pack',
    'hero1_desc' => 'Pure flow. Designed to be felt. Wall-hung rimless ceramic architecture with integrated hydro-wellness, thermal bidet comfort, and soft ambient cyan lighting.', 'hero2_desc' => 'Architectural brassware crafted with titanium vapor deposition. Air-infused laminar streams powered by Swiss Neoperl® precision aerators.', 'hero3_desc' => 'Museum-grade composite stone soaking sanctuaries engineered for ultra-luxury residential projects and boutique hotel suites worldwide.', 'hero4_desc' => 'Concealed 38°C anti-scald hydrotherapy rain showers with illuminated micro-droplet mist and aerospace gunmetal titanium controls.', 'finish_default_title' => 'Brushed Rose Gold (PVD)', 'finish_default_desc' => 'An opulent, warm metallic hue crafted via vacuum plasma PVD. Ultra-resistant to micro-scratches, finger marks, and corrosion in coastal and humid spa environments.', 'finish_base_label' => 'Base Alloy', 'finish_coating_label' => 'Coating Spec', 'finish_cartridge_label' => 'Internal Cartridge', 'finish_aerator_label' => 'Aerator Standard', 'corporate_desc' => 'LUFLY operates modern robotic ceramic kilns and CNC brassware manufacturing facilities headquartered in Gaziantep, Turkey. We engineer sanitary architecture for prestigious hotel projects, high-end developers, and commercial specifiers across the European Union, the Middle East, and beyond.', 'legal_name' => 'Legal Name', 'headquarters' => 'Headquarters', 'compliance' => 'Compliance', 'export_office' => 'Export Office',
    'finish_rose_title' => 'Brushed Rose Gold (PVD)', 'finish_rose_desc' => 'An opulent, warm metallic hue crafted via vacuum plasma PVD.', 'finish_chrome_title' => 'Polished Mirror Chrome', 'finish_chrome_desc' => 'A flawless architectural mirror finish with durable multi-layer plating.', 'finish_gold_title' => 'Brushed Royal Gold (PVD)', 'finish_gold_desc' => 'A luminous champagne-gold finish with directional brushwork.', 'finish_black_title' => 'Matte Obsidian Black', 'finish_black_desc' => 'A tactile, non-reflective black for bold monolithic contrasts.', 'finish_steel_title' => 'Brushed Architectural Steel', 'finish_steel_desc' => 'Industrial precision with a durable hygienic satin surface.', 'finish_gunmetal_title' => 'Gunmetal Titanium Grey', 'finish_gunmetal_desc' => 'A deep charcoal metallic finish for modern spa architecture.',
];
