#!/usr/bin/env python3
"""Regenerate the data section of lufly-database.sql from the SQLite database.

Python twin of `php cli db:export-mysql` (core/Console/Commands/ExportMysqlCommand.php),
used because the sandbox has no PHP runtime. The schema section of the file is
preserved verbatim; only the "Seed / live data" block is rebuilt.
"""
import datetime, os, re, sqlite3

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
DB = os.path.join(ROOT, 'database', 'lufly.sqlite')
OUT = os.path.join(ROOT, 'lufly-database.sql')

TABLE_ORDER = [
    'migrations', 'languages', 'users', 'roles', 'permissions', 'role_permissions',
    'user_roles', 'settings', 'media', 'activity_logs', 'audits', 'api_logs',
    'notifications', 'pages', 'page_translations', 'blogs', 'blog_translations',
    'categories', 'category_translations', 'brands', 'collections',
    'collection_translations', 'products', 'product_translations', 'product_variants',
    'attributes', 'attribute_options', 'product_attribute_values',
    'product_specifications', 'product_dimensions', 'product_media',
    'product_documents', 'product_relations', 'seo_meta', 'product_search_keywords',
    'product_import_logs', 'announcements', 'announcement_translations',
]


def quote(value):
    if value is None:
        return 'NULL'
    if isinstance(value, bool):
        return '1' if value else '0'
    if isinstance(value, (int, float)):
        return str(value)
    escaped = (str(value).replace('\\', '\\\\').replace("'", "\\'")
               .replace('\n', '\\n').replace('\r', '\\r'))
    return f"'{escaped}'"


def main():
    db = sqlite3.connect(DB)
    db.row_factory = sqlite3.Row
    lines = []
    for table in TABLE_ORDER:
        try:
            rows = db.execute(f'SELECT * FROM "{table}" ORDER BY id ASC').fetchall()
        except sqlite3.Error:
            continue
        if not rows:
            continue
        lines.append('')
        lines.append(f'-- data: {table} ({len(rows)} rows)')
        for row in rows:
            cols = ', '.join(f'`{k}`' for k in row.keys())
            vals = ', '.join(quote(row[k]) for k in row.keys())
            lines.append(f'INSERT INTO `{table}` ({cols}) VALUES ({vals});')

    text = open(OUT, encoding='utf-8').read()
    head, _, tail = text.partition('-- Seed / live data\n')
    marker = '-- ====================================================================='
    _, _, rest = tail.partition(marker + '\n')
    _, _, footer = rest.partition('\nSET FOREIGN_KEY_CHECKS = 1;')

    head = re.sub(r'-- Generated by .*', '-- Generated by `php cli db:export-mysql` on '
                  + datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'), head, count=1)

    new = (head + '-- Seed / live data\n' + marker + '\n' + '\n'.join(lines)
           + '\nSET FOREIGN_KEY_CHECKS = 1;' + footer)
    open(OUT, 'w', encoding='utf-8').write(new)
    print('wrote', OUT, len(lines), 'data lines')


if __name__ == '__main__':
    raise SystemExit(main())
