<?php

declare(strict_types=1);

return [
    'hero_title' => 'Lufly Platformu',
    'hero_subtitle' => 'Saf PHP ile geliştirilmiş, modüler, güvenli ve ölçeklenebilir kurumsal çok dilli altyapı.',
    'cta_products' => 'Ürünleri incele',
    'cta_admin' => 'Yönetim panelini aç',
    'features_title' => 'Neler içeriyor',
    'feature_modules' => 'Modüler mimari',
    'feature_modules_desc' => 'Ürünler, kullanıcılar, medya, ayarlar ve daha fazlası — her modül kendi denetleyici, servis ve deposuyla gelir.',
    'feature_localization' => 'Sınırsız yerelleştirme',
    'feature_localization_desc' => 'Statik çeviriler, dinamik içerik çevirileri ve tamamen çevrilmiş URL yapıları.',
    'feature_api' => 'Standartlara dayalı API',
    'feature_api_desc' => 'Tutarlı başarı/hata zarfları, sayfalama meta verisi ve otomatik üretilen dokümantasyon.',
    'hero1_eyebrow' => 'LUFLY · TIDAL MONOLITH SİSTEMİ', 'hero1_primary' => 'Akıllı Klozetleri Gör', 'whatsapp_specifier' => 'WhatsApp Uzmanı',
    'hero2_eyebrow' => 'LUFLY · HİDRODİNAMİK AKIŞ', 'hero2_primary' => 'Tüm Bataryaları Gör', 'hero2_secondary' => '6 PVD Kaplamayı İncele',
    'hero3_eyebrow' => 'LUFLY · MEKANSAL MİMARİ', 'hero3_primary' => 'Koleksiyonları Keşfet', 'hero3_secondary' => 'BIM Modellerini İste',
    'hero4_eyebrow' => 'LUFLY · HİDROTERAPİ RAHATLIĞI', 'hero4_primary' => 'Duşları Keşfet', 'hero4_secondary' => 'Hidrodinamik Ritüeller',
    'trust_kicker' => 'Avantajımız', 'trust_title_before' => 'Daha iyi bir', 'trust_title_emphasis' => 'Yarın', 'trust_title_after' => 'için tasarlandı', 'trust_subtitle' => 'Avrupa kalitesi. Sürdürülebilir yenilik. Küresel erişim.', 'year' => 'YIL',
    'trust_guarantee_title' => 'Fabrika Garantisi', 'trust_guarantee_desc' => '400 kg yük toleranslı, Avrupa EN 997 ve EN 817 kalite sertifikasyonu.', 'trust_water_title' => 'PRO-ECO Hidrodinamik', 'trust_water_desc' => 'İsviçre Neoperl® hassas aeratörleri, debiyi korurken %45ʼe kadar su tasarrufu sağlar.', 'trust_ceramic_title' => 'Vitrifiye Seramik', 'trust_ceramic_desc' => 'Gözeneksiz nano-antibakteriyel sır ile %0,35ʼin altında su emilimi.', 'trust_global_title' => 'Küresel Pazarlar', 'trust_global_desc' => 'Gaziantep üretim tesislerinden 34ʼten fazla küresel pazara stratejik ihracat.', 'trust_footer' => 'Bugünün kalitesi. Daha temiz bir yarın.',
    'finishes_tag' => 'Yüzey Metalurjisi ve Kaplamalar', 'finishes_title_before' => 'Mekanınızın', 'finishes_title_emphasis' => 'Kaplamasını', 'finishes_title_after' => 'Seçin', 'finishes_desc' => 'Olağanüstü dayanıklılık, zarif estetik ve çizilme, korozyon ve zorlu ortamlara uzun süreli direnç için Fiziksel Buhar Biriktirme (PVD) teknolojisiyle geliştirilen altı mimari kaplama.', 'finishes_note_1' => 'Kaplamalar', 'finishes_note_2' => 'dayanıklı', 'finishes_note_3' => 'güzellik', 'finishes_note_4' => 'kalıcı', 'finish_inquire' => 'Bu Kaplama Hakkında WhatsAppʼtan Bilgi Al', 'view_mixers' => 'Tüm Bataryaları Gör',
    'collections_tag' => 'Seçkin Koleksiyonlar', 'design_title' => 'Mekanınızı Tasarlayın', 'design_desc' => 'Monolitik mimari uyum için tasarlanmış seramik setler, bataryalar ve wellness ürünleri.', 'category_toilets' => 'Klozetler ve Bideler', 'category_toilets_desc' => 'Rimsiz EN 997 Seramik · Yavaş Kapanır', 'category_basins' => 'Lavabolar', 'category_basins_desc' => 'Tezgah Üstü ve Monolitik Lavabolar', 'category_mixers' => 'Bataryalar ve Armatürler', 'category_mixers_desc' => 'Masif Pirinç · PVD Kaplama', 'category_showers' => 'Gizli Duş Sistemleri', 'category_showers_desc' => '38°C Termostatik Güvenlik Sistemi', 'category_commercial' => 'Ticari Sıhhi Tesisat', 'category_commercial_desc' => 'Radar Sensörlü Pisuarlar ve Armatürler',
    'inspiration_tag' => 'Mekansal Sunum', 'inspiration_title' => 'İlham Alın', 'inspiration_desc' => 'Lüks konut ve konaklama projelerinde LUFLY ürünlerinin kullanıldığı gerçek mimari uygulamaları keşfedin.', 'inspiration_1_tag' => 'Spa ve Wellness', 'inspiration_1_title' => 'Calacatta Yönetici Süiti', 'inspiration_1_desc' => 'Fırçalı altın zemin bataryası ve monolitik vitrifiye ürünlerle eşleşen bağımsız küvet.', 'inspiration_2_tag' => 'Minimalist Yaşam', 'inspiration_2_title' => 'Minimalist Meşe Banyosu', 'inspiration_2_desc' => 'Mat siyah gizli armatürler, doğal mikro beton ve sıcak ahşapla dokunsal bir kontrast oluşturur.', 'inspiration_3_tag' => 'Mimari Misafir Banyosu', 'inspiration_3_title' => 'Sakin Japandi Kaçamağı', 'inspiration_3_desc' => 'Yüksek rose gold batarya ve atmosferik aydınlatmayla tamamlanan beyaz seramik lavabo.', 'inspiration_4_tag' => 'Gurme Mimarisi', 'inspiration_4_title' => 'Çağdaş Mutfak Süiti', 'inspiration_4_desc' => 'Kompozit kuvars evye üzerinde fırçalı çelik, çift püskürtmeli mimari mutfak bataryası.',
    'rituals_tag' => 'Hidrodinamik Mühendislik', 'rituals_title' => 'Hassasiyetle Şekillenen Su Ritüelleri', 'rituals_desc' => 'Her damla duyusal konfor, sessiz çalışma ve sorumlu tasarruf sağlayacak şekilde tasarlanır.', 'ritual_1_label' => 'HİDRODİNAMİK AKIŞ', 'ritual_1_title' => 'Hava Takviyeli Kristal Akış', 'ritual_1_desc' => 'Hassas havalandırma su akışına mikro hava kabarcıkları ekleyerek sıçramayı azaltan yoğun ve kadifemsi bir akış oluşturur; su tüketimini %45ʼe kadar düşürür.', 'ritual_1_metric' => 'Pro-Eco 5,7 L/dk Standardı', 'ritual_2_label' => 'SERAMİK DİSKLER', 'ritual_2_title' => '500.000 Döngü Dayanıklılığı', 'ritual_2_desc' => 'Kerox® Hungary elmas sertliğindeki seramik diskleri sızdırmaz çalışma, yumuşak kol hareketi ve kireç direnci sağlar.', 'ritual_2_metric' => 'Sıfır Sapma · Sınıf 1 Akustik', 'ritual_3_label' => 'TERMOSTAT GÜVENLİĞİ', 'ritual_3_title' => 'Anında 0,2 sn Sıcaklık Dengesi', 'ritual_3_desc' => 'Gizli termostatik kartuşlar basınç değişimlerine 0,2 saniyede yanıt verir ve suyu 38°Cʼde sabitler.', 'ritual_3_metric' => '38°C Güvenlik Kilidi Standardı',
    'featured_tag' => 'Başyapıt Arşivi', 'featured_title' => 'Öne Çıkan Mimari Ürünler', 'full_catalog' => 'Tüm Kataloğu Gör (280+ Ürün)', 'inquire_b2b' => 'B2B Bilgi Al', 'corporate_badge' => 'Resmi Üretici Kuruluş', 'spec_desk_title' => 'Mimari Teknik Destek Masası', 'spec_desk_cta' => 'Mimar İhale Paketini İste',
    'hero1_desc' => 'Hissedilmek üzere tasarlanmış saf akış. Entegre hidro wellness, termal bide konforu ve yumuşak camgöbeği aydınlatmalı duvara asılı rimsiz seramik mimari.', 'hero2_desc' => 'Titanyum buhar biriktirme ile üretilen mimari pirinç armatürler. Swiss Neoperl® hassas aeratörleriyle güçlendirilen hava katkılı laminer akışlar.', 'hero3_desc' => 'Ultra lüks konut projeleri ve dünya çapındaki butik otel süitleri için tasarlanmış müze kalitesinde kompozit taş dinlenme alanları.', 'hero4_desc' => 'Aydınlatılmış mikro damlacık sisi ve havacılık sınıfı gunmetal titanyum kumandalı, gizli 38°C haşlanma önleyici hidroterapi yağmur duşları.', 'finish_default_title' => 'Fırçalı Rose Gold (PVD)', 'finish_default_desc' => 'Vakum plazma PVD ile üretilen zengin ve sıcak metalik ton. Mikro çiziklere, parmak izlerine ve neme karşı son derece dayanıklıdır.', 'finish_base_label' => 'Ana Alaşım', 'finish_coating_label' => 'Kaplama Özelliği', 'finish_cartridge_label' => 'İç Kartuş', 'finish_aerator_label' => 'Aeratör Standardı', 'corporate_desc' => 'LUFLY, merkezi Gaziantepʼte bulunan modern robotik seramik fırınları ve CNC pirinç armatür üretim tesisleri işletir. Avrupa Birliği, Orta Doğu ve ötesindeki prestijli otel projeleri ve geliştiriciler için sıhhi mimari tasarlarız.', 'legal_name' => 'Yasal Ad', 'headquarters' => 'Merkez', 'compliance' => 'Uygunluk', 'export_office' => 'İhracat Ofisi',
    'finish_rose_title' => 'Fırçalı Rose Gold (PVD)', 'finish_rose_desc' => 'Vakum plazma PVD ile üretilen zengin ve sıcak metalik ton.', 'finish_chrome_title' => 'Parlak Ayna Krom', 'finish_chrome_desc' => 'Dayanıklı çok katmanlı kaplamaya sahip kusursuz mimari ayna yüzey.', 'finish_gold_title' => 'Fırçalı Kraliyet Altını (PVD)', 'finish_gold_desc' => 'Yönlü fırça izlerine sahip aydınlık şampanya altını kaplama.', 'finish_black_title' => 'Mat Obsidyen Siyah', 'finish_black_desc' => 'Cesur monolitik kontrastlar için dokunsal, yansımasız siyah.', 'finish_steel_title' => 'Fırçalı Mimari Çelik', 'finish_steel_desc' => 'Dayanıklı hijyenik saten yüzeyle endüstriyel hassasiyet.', 'finish_gunmetal_title' => 'Gunmetal Titanyum Gri', 'finish_gunmetal_desc' => 'Modern spa mimarisi için koyu antrasit metalik kaplama.',
];
