<?php

declare(strict_types=1);

namespace Core\Console\Commands;

use Core\Console\Command;
use Core\Console\SchemaDiscovery;
use Core\Database\DatabaseManager;

/**
 * Builds lufly-database.sql - a phpMyAdmin / XAMPP ready MySQL dump with the
 * full schema (all tables, indexes, foreign keys) plus every seed row that
 * currently lives in the active database (typically the seeded sqlite copy).
 *
 * Usage:
 *   php cli db:export-mysql                     # -> lufly-database.sql
 *   php cli db:export-mysql --out=path/to.sql
 */
final class ExportMysqlCommand extends Command
{
    protected string $name = 'db:export-mysql';

    protected string $description = 'Export schema + data as lufly-database.sql (MySQL / phpMyAdmin / XAMPP ready).';

    /**
     * Creation order (parents first). Drops use the reverse order.
     *
     * @var string[]
     */
    private const TABLE_ORDER = [
        'migrations',
        'languages',
        'users',
        'roles',
        'permissions',
        'role_permissions',
        'user_roles',
        'settings',
        'media',
        'activity_logs',
        'audits',
        'api_logs',
        'notifications',
        'pages',
        'page_translations',
        'blogs',
        'blog_translations',
        'categories',
        'category_translations',
        'brands',
        'collections',
        'collection_translations',
        'products',
        'product_translations',
        'product_variants',
        'attributes',
        'attribute_options',
        'product_attribute_values',
        'product_specifications',
        'product_dimensions',
        'product_media',
        'product_documents',
        'product_relations',
        'seo_meta',
        'product_search_keywords',
        'product_import_logs',
        'announcements',
        'announcement_translations',
        'ai_cache',
        'ai_usage',
        'favorites',
        'favorite_items',
    ];

    public function handle(array $args, array $options): int
    {
        $database = new DatabaseManager();
        $source = $database->connection();

        $out = (string) ($options['out'] ?? $this->app->basePath('lufly-database.sql'));

        $sql = [];
        $sql[] = '-- =====================================================================';
        $sql[] = '-- LUFLY Platform - full database export';
        $sql[] = '-- File: lufly-database.sql';
        $sql[] = '-- Target: MySQL 5.7+ / MySQL 8.x / MariaDB 10.4+ (XAMPP, phpMyAdmin import)';
        $sql[] = '-- Generated by `php cli db:export-mysql` on ' . date('Y-m-d H:i:s');
        $sql[] = '--';
        $sql[] = '-- Import: phpMyAdmin -> Import -> choose this file (or:';
        $sql[] = '--   mysql -u root < lufly-database.sql';
        $sql[] = '-- ). The database "lufly" is created automatically.';
        $sql[] = '-- =====================================================================';
        $sql[] = '';
        $sql[] = 'SET NAMES utf8mb4;';
        $sql[] = "SET time_zone = '+00:00';";
        $sql[] = 'SET FOREIGN_KEY_CHECKS = 0;';
        $sql[] = "SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';";
        $sql[] = '';
        $sql[] = 'CREATE DATABASE IF NOT EXISTS `lufly` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;';
        $sql[] = 'USE `lufly`;';
        $sql[] = '';

        $definitions = [];
        foreach (SchemaDiscovery::definitions($this->app->basePath('database/schema')) as $definition) {
            $definitions[$definition->tableName()] = $definition;
        }

        foreach (self::TABLE_ORDER as $table) {
            $sql[] = 'DROP TABLE IF EXISTS `' . $table . '`;';
        }
        $sql[] = '';

        foreach (self::TABLE_ORDER as $table) {
            if ($table === 'migrations') {
                $sql[] = '-- table: migrations';
                $sql[] = <<<'DDL'
CREATE TABLE `migrations` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `migration` VARCHAR(255) NOT NULL,
    `batch` INTEGER NOT NULL,
    `applied_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DDL;
                $sql[] = '';
                continue;
            }

            $definition = $definitions[$table] ?? null;
            if ($definition === null) {
                $this->line("-- skipping {$table} (no schema definition)");
                continue;
            }

            $sql[] = '-- table: ' . $table;
            foreach ($definition->blueprint()->toStatements('mysql') as $statement) {
                $sql[] = $statement . ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;';
            }
            $sql[] = '';
        }

        /* --------------------------------------------------------------- data */
        $sql[] = '';
        $sql[] = '-- =====================================================================';
        $sql[] = '-- Seed / live data';
        $sql[] = '-- =====================================================================';

        foreach (self::TABLE_ORDER as $table) {
            $exists = $table === 'migrations'
                ? $source->selectOne("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?", [$table]) !== null
                || $source->selectOne('SHOW TABLES LIKE ?', [$table]) !== null
                : true;

            if (!$exists) {
                continue;
            }

            try {
                $rows = $source->select("SELECT * FROM {$table} ORDER BY id ASC");
            } catch (\Throwable) {
                $this->line("-- no data exported for {$table}");
                continue;
            }

            if ($rows === []) {
                continue;
            }

            $sql[] = '';
            $sql[] = '-- data: ' . $table . ' (' . count($rows) . ' rows)';

            foreach ($rows as $row) {
                $sql[] = $this->insertStatement($table, $row);
            }
        }

        $sql[] = '';
        $sql[] = 'SET FOREIGN_KEY_CHECKS = 1;';
        $sql[] = '';
        $sql[] = '-- End of lufly-database.sql';

        file_put_contents($out, implode(PHP_EOL, $sql) . PHP_EOL);

        $this->success('Wrote MySQL export to ' . $out);

        return 0;
    }

    /** @param array<string, mixed> $row */
    private function insertStatement(string $table, array $row): string
    {
        $columns = [];
        $values = [];

        foreach ($row as $column => $value) {
            $columns[] = '`' . str_replace('`', '', (string) $column) . '`';
            $values[] = $this->quoteValue($value);
        }

        return sprintf(
            'INSERT INTO `%s` (%s) VALUES (%s);',
            $table,
            implode(', ', $columns),
            implode(', ', $values),
        );
    }

    private function quoteValue(mixed $value): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        return "'" . $this->escape((string) $value) . "'";
    }

    private function escape(string $value): string
    {
        return str_replace(
            ['\\', "\0", "\n", "\r", "\x1a", "'"],
            ['\\\\', '\\0', '\\n', '\\r', '\\Z', "\\'"],
            $value,
        );
    }
}
