-- Generated by `php cli schema:dump` (driver: sqlite)

-- table: activity_logs
CREATE TABLE activity_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NULL,
    action VARCHAR(50) NOT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) NULL,
    description VARCHAR(255) NULL,
    data JSON NULL,
    created_at DATETIME NULL
);
CREATE INDEX activity_logs_user_id_index ON activity_logs (user_id);
CREATE INDEX activity_logs_action_index ON activity_logs (action);
CREATE INDEX activity_logs_entity_index ON activity_logs (entity);

-- table: api_logs
CREATE TABLE api_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    endpoint VARCHAR(255) NOT NULL,
    method VARCHAR(50) NOT NULL,
    status_code INTEGER NOT NULL,
    response_time_ms INTEGER NOT NULL DEFAULT 0,
    ip VARCHAR(50) NOT NULL,
    created_at DATETIME NULL
);
CREATE INDEX api_logs_endpoint_index ON api_logs (endpoint);

-- table: audits
CREATE TABLE audits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) NULL,
    action VARCHAR(50) NOT NULL,
    before JSON NULL,
    after JSON NULL,
    created_at DATETIME NULL
);
CREATE INDEX audits_user_id_index ON audits (user_id);
CREATE INDEX audits_entity_index ON audits (entity);
CREATE INDEX audits_entity_id_index ON audits (entity_id);

-- table: blog_translations
CREATE TABLE blog_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    blog_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    excerpt VARCHAR(255) NULL,
    content LONGTEXT NULL,
    FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX blog_translations_blog_id_locale_unique ON blog_translations (blog_id, locale);
CREATE INDEX blog_translations_locale_index ON blog_translations (locale);

-- table: blogs
CREATE TABLE blogs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id BIGINT NULL,
    published_at DATETIME NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX blogs_author_id_index ON blogs (author_id);
CREATE INDEX blogs_slug_index ON blogs (slug);
CREATE INDEX blogs_status_index ON blogs (status);
CREATE INDEX blogs_deleted_at_index ON blogs (deleted_at);

-- table: categories
CREATE TABLE categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_id BIGINT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    image VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX categories_parent_id_index ON categories (parent_id);
CREATE INDEX categories_slug_index ON categories (slug);
CREATE INDEX categories_status_index ON categories (status);
CREATE INDEX categories_deleted_at_index ON categories (deleted_at);

-- table: category_translations
CREATE TABLE category_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description LONGTEXT NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX category_translations_category_id_locale_unique ON category_translations (category_id, locale);
CREATE INDEX category_translations_locale_index ON category_translations (locale);

-- table: languages
CREATE TABLE languages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100) NOT NULL,
    dir VARCHAR(50) NOT NULL DEFAULT 'ltr',
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX languages_deleted_at_index ON languages (deleted_at);

-- table: media
CREATE TABLE media (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    collection VARCHAR(50) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    extension VARCHAR(50) NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    meta JSON NULL,
    owner_id BIGINT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX media_collection_index ON media (collection);
CREATE INDEX media_status_index ON media (status);
CREATE INDEX media_deleted_at_index ON media (deleted_at);

-- table: notifications
CREATE TABLE notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'info',
    title VARCHAR(255) NOT NULL,
    body LONGTEXT NOT NULL,
    data JSON NULL,
    read_at DATETIME NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- table: page_translations
CREATE TABLE page_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    page_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT NULL,
    FOREIGN KEY (page_id) REFERENCES pages (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX page_translations_page_id_locale_unique ON page_translations (page_id, locale);
CREATE INDEX page_translations_locale_index ON page_translations (locale);

-- table: pages
CREATE TABLE pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX pages_slug_index ON pages (slug);
CREATE INDEX pages_status_index ON pages (status);
CREATE INDEX pages_deleted_at_index ON pages (deleted_at);

-- table: permissions
CREATE TABLE permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
);

-- table: product_translations
CREATE TABLE product_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    short_description VARCHAR(255) NULL,
    description LONGTEXT NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_translations_product_id_locale_unique ON product_translations (product_id, locale);
CREATE INDEX product_translations_locale_index ON product_translations (locale);

-- table: products
CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_id BIGINT NULL,
    sku VARCHAR(100) NOT NULL UNIQUE,
    slug VARCHAR(255) NOT NULL UNIQUE,
    price DECIMAL(12,2) NOT NULL DEFAULT 0,
    image VARCHAR(255) NULL,
    specs JSON NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL
);
CREATE INDEX products_slug_index ON products (slug);
CREATE INDEX products_status_index ON products (status);
CREATE INDEX products_deleted_at_index ON products (deleted_at);

-- table: role_permissions
CREATE TABLE role_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX role_permissions_role_id_permission_id_unique ON role_permissions (role_id, permission_id);

-- table: roles
CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX roles_deleted_at_index ON roles (deleted_at);

-- table: settings
CREATE TABLE settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(100) NOT NULL UNIQUE,
    value JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
);

-- table: user_roles
CREATE TABLE user_roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX user_roles_user_id_role_id_unique ON user_roles (user_id, role_id);

-- table: users
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NULL,
    locale VARCHAR(50) NULL DEFAULT 'en',
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX users_status_index ON users (status);
CREATE INDEX users_deleted_at_index ON users (deleted_at);
