-- Generated by `php cli schema:dump` (driver: sqlite)

-- table: activity_logs
CREATE TABLE activity_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NULL,
    action VARCHAR(50) NOT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) NULL,
    description VARCHAR(255) NULL,
    data JSON NULL,
    created_at DATETIME NULL
);
CREATE INDEX activity_logs_user_id_index ON activity_logs (user_id);
CREATE INDEX activity_logs_action_index ON activity_logs (action);
CREATE INDEX activity_logs_entity_index ON activity_logs (entity);

-- table: announcement_translations
CREATE TABLE announcement_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    announcement_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    message VARCHAR(500) NOT NULL,
    cta_label VARCHAR(150) NULL,
    FOREIGN KEY (announcement_id) REFERENCES announcements (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX announcement_translations_announcement_id_locale_unique ON announcement_translations (announcement_id, locale);
CREATE INDEX announcement_translations_announcement_id_index ON announcement_translations (announcement_id);
CREATE INDEX announcement_translations_locale_index ON announcement_translations (locale);

-- table: announcements
CREATE TABLE announcements (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    placement VARCHAR(50) NOT NULL DEFAULT 'topbar',
    style VARCHAR(50) NOT NULL DEFAULT 'promo',
    link_url VARCHAR(255) NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX announcements_placement_index ON announcements (placement);
CREATE INDEX announcements_style_index ON announcements (style);
CREATE INDEX announcements_is_active_index ON announcements (is_active);
CREATE INDEX announcements_deleted_at_index ON announcements (deleted_at);

-- table: api_logs
CREATE TABLE api_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    endpoint VARCHAR(255) NOT NULL,
    method VARCHAR(50) NOT NULL,
    status_code INTEGER NOT NULL,
    response_time_ms INTEGER NOT NULL DEFAULT 0,
    ip VARCHAR(50) NOT NULL,
    created_at DATETIME NULL
);
CREATE INDEX api_logs_endpoint_index ON api_logs (endpoint);

-- table: attribute_options
CREATE TABLE attribute_options (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attribute_id BIGINT NOT NULL,
    value VARCHAR(150) NOT NULL,
    color_hex VARCHAR(50) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX attribute_options_attribute_id_value_unique ON attribute_options (attribute_id, value);
CREATE INDEX attribute_options_attribute_id_index ON attribute_options (attribute_id);

-- table: attributes
CREATE TABLE attributes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'select',
    is_filterable TINYINT(1) NOT NULL DEFAULT 1,
    is_sortable TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX attributes_deleted_at_index ON attributes (deleted_at);

-- table: audits
CREATE TABLE audits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NULL,
    entity VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50) NULL,
    action VARCHAR(50) NOT NULL,
    before JSON NULL,
    after JSON NULL,
    created_at DATETIME NULL
);
CREATE INDEX audits_user_id_index ON audits (user_id);
CREATE INDEX audits_entity_index ON audits (entity);
CREATE INDEX audits_entity_id_index ON audits (entity_id);

-- table: blog_translations
CREATE TABLE blog_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    blog_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    excerpt VARCHAR(255) NULL,
    content LONGTEXT NULL,
    FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX blog_translations_blog_id_locale_unique ON blog_translations (blog_id, locale);
CREATE INDEX blog_translations_locale_index ON blog_translations (locale);

-- table: blogs
CREATE TABLE blogs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id BIGINT NULL,
    published_at DATETIME NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX blogs_author_id_index ON blogs (author_id);
CREATE INDEX blogs_slug_index ON blogs (slug);
CREATE INDEX blogs_status_index ON blogs (status);
CREATE INDEX blogs_deleted_at_index ON blogs (deleted_at);

-- table: brands
CREATE TABLE brands (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    logo VARCHAR(255) NULL,
    country VARCHAR(100) NULL,
    website VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX brands_slug_index ON brands (slug);
CREATE INDEX brands_status_index ON brands (status);
CREATE INDEX brands_deleted_at_index ON brands (deleted_at);

-- table: categories
CREATE TABLE categories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_id BIGINT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    image VARCHAR(255) NULL,
    icon VARCHAR(255) NULL,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX categories_parent_id_index ON categories (parent_id);
CREATE INDEX categories_slug_index ON categories (slug);
CREATE INDEX categories_is_featured_index ON categories (is_featured);
CREATE INDEX categories_status_index ON categories (status);
CREATE INDEX categories_deleted_at_index ON categories (deleted_at);

-- table: category_translations
CREATE TABLE category_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description LONGTEXT NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX category_translations_category_id_locale_unique ON category_translations (category_id, locale);
CREATE INDEX category_translations_locale_index ON category_translations (locale);

-- table: collection_translations
CREATE TABLE collection_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    collection_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description LONGTEXT NULL,
    FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX collection_translations_collection_id_locale_unique ON collection_translations (collection_id, locale);
CREATE INDEX collection_translations_locale_index ON collection_translations (locale);

-- table: collections
CREATE TABLE collections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug VARCHAR(255) NOT NULL UNIQUE,
    image VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX collections_slug_index ON collections (slug);
CREATE INDEX collections_status_index ON collections (status);
CREATE INDEX collections_deleted_at_index ON collections (deleted_at);

-- table: languages
CREATE TABLE languages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    native_name VARCHAR(100) NOT NULL,
    dir VARCHAR(50) NOT NULL DEFAULT 'ltr',
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX languages_deleted_at_index ON languages (deleted_at);

-- table: media
CREATE TABLE media (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid CHAR(36) NULL,
    collection VARCHAR(50) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    extension VARCHAR(50) NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    width INTEGER NULL,
    height INTEGER NULL,
    meta JSON NULL,
    owner_id BIGINT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL
);
CREATE INDEX media_uuid_index ON media (uuid);
CREATE INDEX media_collection_index ON media (collection);
CREATE INDEX media_status_index ON media (status);
CREATE INDEX media_deleted_at_index ON media (deleted_at);

-- table: notifications
CREATE TABLE notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'info',
    title VARCHAR(255) NOT NULL,
    body LONGTEXT NOT NULL,
    data JSON NULL,
    read_at DATETIME NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- table: page_translations
CREATE TABLE page_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    page_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content LONGTEXT NULL,
    FOREIGN KEY (page_id) REFERENCES pages (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX page_translations_page_id_locale_unique ON page_translations (page_id, locale);
CREATE INDEX page_translations_locale_index ON page_translations (locale);

-- table: pages
CREATE TABLE pages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    seo JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX pages_slug_index ON pages (slug);
CREATE INDEX pages_status_index ON pages (status);
CREATE INDEX pages_deleted_at_index ON pages (deleted_at);

-- table: permissions
CREATE TABLE permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
);

-- table: product_attribute_values
CREATE TABLE product_attribute_values (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    variant_id BIGINT NULL,
    attribute_id BIGINT NOT NULL,
    attribute_option_id BIGINT NULL,
    custom_value VARCHAR(255) NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    FOREIGN KEY (attribute_id) REFERENCES attributes (id) ON DELETE CASCADE,
    FOREIGN KEY (attribute_option_id) REFERENCES attribute_options (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_attribute_values_product_id_variant_id_attribute_id_attribute_option_id_unique ON product_attribute_values (product_id, variant_id, attribute_id, attribute_option_id);
CREATE INDEX product_attribute_values_product_id_index ON product_attribute_values (product_id);
CREATE INDEX product_attribute_values_variant_id_index ON product_attribute_values (variant_id);
CREATE INDEX product_attribute_values_attribute_id_index ON product_attribute_values (attribute_id);

-- table: product_dimensions
CREATE TABLE product_dimensions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    variant_id BIGINT NULL,
    width_mm DECIMAL(10,2) NULL,
    height_mm DECIMAL(10,2) NULL,
    depth_mm DECIMAL(10,2) NULL,
    weight_kg DECIMAL(10,2) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_dimensions_product_id_variant_id_unique ON product_dimensions (product_id, variant_id);
CREATE INDEX product_dimensions_product_id_index ON product_dimensions (product_id);
CREATE INDEX product_dimensions_variant_id_index ON product_dimensions (variant_id);

-- table: product_documents
CREATE TABLE product_documents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    variant_id BIGINT NULL,
    media_id BIGINT NULL,
    document_type VARCHAR(50) NOT NULL DEFAULT 'catalog',
    language VARCHAR(50) NOT NULL DEFAULT 'en',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
);
CREATE INDEX product_documents_product_id_index ON product_documents (product_id);
CREATE INDEX product_documents_variant_id_index ON product_documents (variant_id);
CREATE INDEX product_documents_media_id_index ON product_documents (media_id);

-- table: product_import_logs
CREATE TABLE product_import_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NULL,
    source_file VARCHAR(255) NULL,
    source_page INTEGER NULL,
    detected_sku VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    raw_data LONGTEXT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE SET NULL
);
CREATE INDEX product_import_logs_product_id_index ON product_import_logs (product_id);
CREATE INDEX product_import_logs_status_index ON product_import_logs (status);

-- table: product_media
CREATE TABLE product_media (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    variant_id BIGINT NULL,
    media_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'gallery',
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_media_product_id_variant_id_media_id_type_unique ON product_media (product_id, variant_id, media_id, type);
CREATE INDEX product_media_product_id_index ON product_media (product_id);
CREATE INDEX product_media_variant_id_index ON product_media (variant_id);
CREATE INDEX product_media_media_id_index ON product_media (media_id);

-- table: product_relations
CREATE TABLE product_relations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    related_product_id BIGINT NOT NULL,
    relation_type VARCHAR(50) NOT NULL DEFAULT 'related',
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (related_product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_relations_product_id_related_product_id_relation_type_unique ON product_relations (product_id, related_product_id, relation_type);
CREATE INDEX product_relations_product_id_index ON product_relations (product_id);
CREATE INDEX product_relations_related_product_id_index ON product_relations (related_product_id);

-- table: product_search_keywords
CREATE TABLE product_search_keywords (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    keyword VARCHAR(150) NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX product_search_keywords_keyword_index ON product_search_keywords (keyword);
CREATE UNIQUE INDEX product_search_keywords_product_id_keyword_unique ON product_search_keywords (product_id, keyword);
CREATE INDEX product_search_keywords_product_id_index ON product_search_keywords (product_id);

-- table: product_specifications
CREATE TABLE product_specifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    variant_id BIGINT NULL,
    spec_key VARCHAR(150) NOT NULL,
    spec_value VARCHAR(255) NOT NULL,
    unit VARCHAR(50) NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE
);
CREATE INDEX product_specifications_spec_key_index ON product_specifications (spec_key);
CREATE INDEX product_specifications_product_id_index ON product_specifications (product_id);
CREATE INDEX product_specifications_variant_id_index ON product_specifications (variant_id);

-- table: product_translations
CREATE TABLE product_translations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    short_description VARCHAR(255) NULL,
    description LONGTEXT NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_translations_product_id_locale_unique ON product_translations (product_id, locale);
CREATE INDEX product_translations_locale_index ON product_translations (locale);

-- table: product_variants
CREATE TABLE product_variants (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    sku VARCHAR(100) NOT NULL UNIQUE,
    variant_name VARCHAR(150) NULL,
    price DECIMAL(12,2) NOT NULL DEFAULT 0,
    stock_status VARCHAR(50) NOT NULL DEFAULT 'in_stock',
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE INDEX product_variants_product_id_index ON product_variants (product_id);
CREATE INDEX product_variants_stock_status_index ON product_variants (stock_status);
CREATE INDEX product_variants_status_index ON product_variants (status);
CREATE INDEX product_variants_deleted_at_index ON product_variants (deleted_at);

-- table: products
CREATE TABLE products (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    model_code VARCHAR(100) NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    category_id BIGINT NULL,
    collection_id BIGINT NULL,
    brand_id BIGINT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL,
    FOREIGN KEY (collection_id) REFERENCES collections (id) ON DELETE SET NULL,
    FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE SET NULL
);
CREATE INDEX products_model_code_index ON products (model_code);
CREATE INDEX products_slug_index ON products (slug);
CREATE INDEX products_category_id_index ON products (category_id);
CREATE INDEX products_collection_id_index ON products (collection_id);
CREATE INDEX products_brand_id_index ON products (brand_id);
CREATE INDEX products_status_index ON products (status);
CREATE INDEX products_is_featured_index ON products (is_featured);
CREATE INDEX products_deleted_at_index ON products (deleted_at);

-- table: role_permissions
CREATE TABLE role_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX role_permissions_role_id_permission_id_unique ON role_permissions (role_id, permission_id);

-- table: roles
CREATE TABLE roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX roles_deleted_at_index ON roles (deleted_at);

-- table: seo_meta
CREATE TABLE seo_meta (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id BIGINT NOT NULL,
    locale VARCHAR(50) NOT NULL,
    meta_title VARCHAR(255) NULL,
    meta_description VARCHAR(500) NULL,
    og_title VARCHAR(255) NULL,
    og_description VARCHAR(500) NULL,
    canonical_url VARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX seo_meta_product_id_locale_unique ON seo_meta (product_id, locale);
CREATE INDEX seo_meta_product_id_index ON seo_meta (product_id);
CREATE INDEX seo_meta_locale_index ON seo_meta (locale);

-- table: settings
CREATE TABLE settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    key VARCHAR(100) NOT NULL UNIQUE,
    value JSON NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
);

-- table: user_roles
CREATE TABLE user_roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX user_roles_user_id_role_id_unique ON user_roles (user_id, role_id);

-- table: users
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NULL,
    locale VARCHAR(50) NULL DEFAULT 'en',
    status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL
);
CREATE INDEX users_status_index ON users (status);
CREATE INDEX users_deleted_at_index ON users (deleted_at);
